; generated by PrusaSlicer 2.6.1+linux-x64-GTK3 on 2023-11-17 at 20:13:56 UTC


;
; thumbnail begin 160x120 6916
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAAUCklEQVR4Ae2dWYwU1xWG6z0PtnEkJ1
; LykodEfnESJ7bkKMpT/GDHDiiRbQXMPjDADPu+DwPDPgz7DDtms9n3fREEzCLZBowQtjFmxywGzL5K
; N/4uup2amq7u6lpvzdyHXyzT0911669zzn/OuedaTZs2FW5o0aKFqKmpEYsXLxZ9+vQRzZo1E7lenw
; /8vhOtWrUSM2fOFAsWLBDdu3fP+pq0oXnz5uKTTz4Rc+fOFQMHDpTrGPZntGzZUq7b/PnzRc+ePcWH
; H34Y6zWGBcuNLF27dpWLOGPGDFFUVBQ68ZzgRi1fvlyMHj1aLq7uC+eGbt26iS1btoiJEyeKTp06SW
; IEQb7PwzBs3rxZlJeXi9atW6dijXISkP+cMGGCJF9ZWZl8mqMmnwJEX7RokZgzZ468eTouWC6yVFdX
; y3WDDFj2oOTzSlCIt2zZMvn5nTt31nLdsmHAgAG1CVhcXCwWLlwozXpJSUlsxLMDwmMFP/74YzFkyB
; D576QWyCsJ2rdvL9atWyemTZsmw4g4iJcNI0aMEKtWrRKDBg3S2otwTzEy58+f/z8Bhw0bJl3g2LFj
; 5ZePm3hOlJaWyu/DTW3btm3ki+Lnhpe0aCJqhhSJNWvWiDFjxsjvmRT5FDAiPAxVVVXy717ceJwgtN
; u5c6e4ffu2ePLkibBwFbNmzZKuj2CWFyVJPDt4ECAg3613796hLmaQmwzxqtv+XhztaEks6vZX+VQn
; TT4FRM/UqVPluhEjOr9bFPfKC3govvnmG3H//n3x6NEjsX37dmEtXbpU3uQ2bdokbvXcwCKuWLFCjB
; 8/XsZWSZDOTr5POz2XIZ/Cf4t/Jn+mCwkB4cCmTZtERUWFq3WO+t4BLDFe4vr165J4ly9flkavXbt2
; wiJe4IvoSDw7eEA++ugjGZ8WEmiHeUOnt3mlDvGc4DVJE88OHlgsITcche72uqjuG6HdkSNHxL1798
; TTp0/FoUOHxNChQzMxqqWr1csGXMnw4cMFVps/3fJrYd9ELNucjq/lJZ/ChvYvJUq6bEDQERvyZz6F
; Hsa94jMQtJcuXRIPHz4UN2/elBkCsht2YVkwAZMgnhMdO3aUF0OSHAUaBekU+rd8Uxzs3Mgz+ewumd
; 9NgmxuIM2FK5wyZYpcw3yv93t/evXqJfbu3Svu3r0rhcZXX30lRRrpIuf7WmkjnwImnGQvVRrySWGL
; AKzejHZ/LJh4urtk1knlefv16ye9SFhE5LXoie+++048ePBAig1i0B49erh6KyttxHNaOy5u5cqVko
; zEiWGRb3/Jc4HJp7M1JI7euHGjtExYRi+/k+ue4FohG6728ePH4sKFC2L69OkZ8eP2e1aayOe2MJh2
; EpuqnhzkxlS3fUWERTzdrSFehHWbN2+efJD9knDUqFHi+PHj0uLhcvft2ydLq7x/PuJaaSaeEwTYlK
; RYEHXxXoHVW1HycmTk01mg4IqxXihWFad5ISLWDUF45coVmV4hzYLw6NChg+cKlqUz+fwsJqKEuHD2
; 7NmeAm0wuvUb4lCXRiJq8unskglfCGVwm1Sh8r2+f//+4uDBg1JokF758ssvZSkwm9AoiIBpJZ4dBL
; zjxo2rVU/O9jqs3qziV2MjnhOLi36TCNncwDrhPUj6212oc23JKZ47d04KjTt37khlTYlNCZpC7rWl
; E/nCXtAuXbrIxaQs5awEQL4Dpc8nRj6drSGeY/369VIt41Hs67ljxw5x69YtKTTOnDkjJk2aJNfWb9
; OIVR+JZwcJUdqUVD3ZWcfVBToKFNaNmI5SKHXcr7/+OlPH3bVrl+jbt28dK1kwAesz+ewgZtm0dLbY
; 1+d32pHPbg11qyfTE/rtt9+KGzduSOJdvXpVdnpjGd1Cm1QQMO6F9FLHNdawNqjZfvHFF5k67unTp6
; Ul9KKUtSZgnIv4rI7759SQTyHJdA1hC40fFy9elHVcYj5i6crKSs/1ZK8kjJWAcS8k5DvY+YVUEc+O
; JAQKPaF79uyR6pakMv17tMGRpsHl0kK1du1aMXnyZJnvC0rC2AgYN/FmtPtDqsiWC3G4ZMhFk8KpU6
; dkegVs3bpVNhY4hQbpFkqfpLkQIvnq8IkSME7iKfKFWcdtCNaQOu6GDRuk0CC9QgsVuyGxdrnIRe6P
; Cgp7ePLVkxMhYNzki7KOW1+tId3Sx44dy9Rx9+/fLwYPHux5Vx+vo0mYmnK+OnysBIyTeFi9eSWvp4
; pIQRCGQCF5jAulPR6hgfVbsmSJtIZeWrScoCUOK0raxk0lx0bAOMmHW4qzjqsLgrhkmg+wdKphlE4W
; SnBKaAQhNdtC6QlkW68XEoZKwDiJh9Wb2f5VkTQRkkYh9WQsG7Hd2bNnpcggv0fJDddZaPeQGyAwW3
; vZUotVzGZNIyFg3OTToY6rC7xYQxpQt23blqnj0kxAjRzxEMWWUiVsSOEgZiIlYJzE07GOqwvcBAqd
; QSdOnJBCA/Lt3r1bWicERJT7mbGqWFyS2qRz7J+VIWDQ0Rdxkm9rya9SRYgkgEBR9WTqtVQwqN9Sx7
; 127ZpUrCSQ/QgNv6AJRA1Qsm+bkASkeVPtLNOVfGmq4+oAXPLkfi3EZ599lqnjHj58WG5lRaEmMcWB
; z6V7Wg1QyhCQLlZ+QOHZbhp1IB9P8uwOf0rVzdcJJyv/JmewoEzp5cPqJT1ChIfAPkBJxoBktFUy0c
; uMubjIl+Y6ri4gRTWk6G2tZtfgcaknU87LiBCIRwcsMYMaUpQE+eTEqSIjNMKGbg2vWGNqz5aTXCQp
; 6R6m1do5Yy4O8tXHOq4u0LHhNWsahryNmvapJpVG/UUaQh1XF+hkDV3zgJhI9olSL0SoRBVD8ETO7f
; SaONrRMogRuuxPzpuIZo8oO+dJJoY9AbSh1nF1gQ478vISkBeRMVf1PWLEoB8a1uAfg3CQpEu2Ckm3
; UE5hmx675/1OgX8mNEwdVzckZQ2tQtMtuGHkM9aQ5GYhH2bquPojbmtYMAEBgoSdUTQwMt4rX10Rq7
; elk6njpgVxChSrUPLZwQgHhgCRN7SPcLCDwT9pWnyDZ4jLJVt+yadALEg3LWPR2Eug0jXPBv+YOm7a
; EfUApcAEVKCrllQN9eRubd83DaP1CFFaQysM8mVIWPSB2FD2TqoW18A7ohAoVljkw+VuK/11qhbUoH
; CEXU8OhYCmYbThISxraAUhX1oH/xiEgzDSNb4JaBpGDUBQgWL5IV59GvxjEA78umSrUPKZhlEDN/ix
; hp4JaBpGDbyiEGuYl4ANbfCPQTjwKlByEtA0jBoEgReXbLlZPTP4xyAs5KonW9nIZ+q4BmHDzRpadu
; KZhlGDqKEEClt+mY6QIaAZ/GMQF5a1+aWc2EXnlCQgI7RqWr8sdrVK14UYpA9bm1ti2Nsvym0dbOmw
; mJDJoMJu3bqJ7k1eESveT9cFGaQDn7a1xMKmL4hRJY3lfnM1GNNixL59Zlvr/zQR4975mbGGBqEB8p
; W91UhMrRwp5w7Zd1RabhMPjDU0CAqIN7+JJUZ2+qfcvFZcXFxnwkbORHTx+2+KGe+m66IN9ADkG9+4
; kSQfwwzcjm7IW4rDJVc0fsm4ZAPPwOoNaPJbMb5iiBztkmvbrudmBFzywn+layEM4oUSGlg9Ju6qk9
; R914KNNTTwCshHemXS2OGiR48enke3FNyQagSKwVEH8ZTQGDlyZM6T1EMjoBIoE9+yxMGidC2YQbjk
; I70yrk9r0adPH08nqYdGQOWSB739krGGDRBYvbLmfxFjhw/yfcChPKYhCAEVSv/9hknXNBBg9RY1ey
; Y0aCbwIjQiJ6Cyhkag1G+oOm7V6GGydBvkgEO1Hz00AioYgVL/gNVb0vxFMbq0iTxoJt9J6l7JFwkB
; lTU09eT6Q77yf/xcrF9cLU/UwvIF5UfkBDTWsH4AoVHR8V3Zu0duj7Y9ZkGieMMgX+QEBKaenD5g9W
; ree1bH5VhX+0nqffv2FStXrpTnAPtJu8ROQOWSjUBJB1Z+8ExoVI4cKhtGswkNlO+CBQvk+YLq5Es/
; 5IuNgHaXbOrJesLeMFpWVpb3JHV+pk5aRZjkywO6zSKPlYDGGupLvmFvNxKTx42o0zCaD8wJ50i3mp
; oa1znhWhHQbg2NQEmeeKqOy5xvGkb9VDRw0xy9yuHn/fv3r2M5c51FkxgBgaknJ0s+1TCKsPAjKJzA
; eiJQIKPa5pHvJK5ECQhMPTl+qIbRcSMGi5KSkkAVjTr38ycis90SkaJyhloTUMHUk6OHvY7LkRpB6r
; j5wEFGHN1Bi5bz3GktCaisoREo0ZGP9MrEMeXySA2/Z/15BeRClBAXcpgRYkV7AioYgRIu8RY2fV6m
; V0ibFNow6pd8zWznTlNJ4dxpdZBRLQLOnDkz1BggLCBQTD05OPloGJ1Y3kv07t07FKFRCPnsIKm9Ys
; UKOREB158hIOxkOgLBqE4EBONHDBSzOr5urKEPqDouJTPcn5/0SljkU8Dtky/kyF8UsyQgX4zcDRlt
; yBi1efZk/X7KR61atUpcu3ZNPHr0SBzdvdoIFI+wC42BAwfWquMmST77eTTsE8Yacgh65pgG2qqZEc
; ONx0QmRT62833++efi3r174unTp/Lv5eXlon3z98RII1Bywt4w2rVr19hCK6/ks0PVk2udE4KJhADr
; 1q2TT0+cxOOzOezw4sWL4uHDh+LWrVvyKaHYjZVWT7GpJ9eFc/BP0IbRqMmnIIcT2U2jAglEpDPdDl
; HLdUA8sGfPHnHnzh3x5MkTcfLkSVFZWemapzINr7XJh9CYMr5C9OrVK5b7FQb5MiLE6Z8VuPnUBzdu
; 3BhKF2w2QC5U0alTp8SDBw8ktm7dKhUb7iPfU9yQ0zXOwT8dOnSIRWiESb6cBFQEofuVZOKkSZNCvU
; Bizg0bNogbN26Ix48fi0uXLsmOW9xHIZ+jGl4bUj3Z6+Af3clXh4DZSAh4uiDgmjVrcrbceAUJ0WPH
; jkmhgcs9cOCALN3gPvzELg2pguIc/BNnDjdM4rkS0I2EXCiZbFQyqtTPBZASWLJkifj++++l0MD68W
; +/G5udwCXX13SNSq8gNHhY8zWMpoF8rgR0IyEgo00ykdJKIaaflp/9+/eLu3fvSqt3/PhxGWOGnaeq
; j9bQ7+Af3cnni4DKktGGvWnTJqm8cr0WchHbnTlzRooM3C6VFwriUbqP+iBQlNDA6lVUVMjwJ06hET
; X5chIwHwkhFuQjd4dFzEYmcnio2h9//FEKjXPnzslkd5RtQHakueE1jME/OhPPEwHzkRDwVFJvJHlN
; LKf+nzLLiRMnxP379yX5yPNR8ou78SGNDa9q8A+50LDiYx3J54mAXkjIArF/dPny5aKqqkq2ZV+9el
; XWcannktCOO0/lRBoaXsMc/KM78QoioBcSAizh2bNnM3Xcw4cPy1gR96FDk4POAoU67sjGvxDTq0YH
; HvyTFvIVRMBcJMSyzZ07V5w/f16mV1C6VDdwwzr2GuokUFTDKIN/KM5TeeKhTUMtN3YCZiMiT+uuXb
; vE7du3ZXoF4uGGifcgJYg7beAFOtSTldCoGtZTlh/JLrCeCDs29tgPEKpvxGvatKmE5fcNuAi239E4
; gNDA8m3fvl0qNmX1SJZyEhMlN/KHupEwSWuoGkbxEs74GOLxENMNRKNG2NesC/l8E5AFW7t2rbh+/b
; oUGpcvXxazZs3K2gbEwlKvJHE9YcKERIWIG+IcoGSv4+Il3Kwc68jPmUZFGTSMUCZp4jnJ54uA9Jsd
; OXIkIzQOHTokewjzuVnawidPnixWr14tiZok4bIhDoHC4J/ef382+IccqRdSkeaqrq6W4y/saa60ES
; 8b+QoiIEqWp5GuFdztzZs35aKwl8RrwAxJqWPS1ABp4yaZF0TR8GpvGOW6C63j4jWov7PeNHJ4/V2d
; iVcQAQmQ9+3bl6njkmCmB01l5+2v9bIwtItTnqPNK+4MvxeEaQ3tg3+C1nGxmvPmzZMiJde2CV2Il4
; 98eQnIxUyfPl2cPn1a1nERG6QJWEgVy7n9Xj6wgDzN1JN5v6TIlgtBBErQA1zcAIHZPEbSnwYPXYnn
; hXw5CUi8sXnz5kwd98KFC2LatGmZ7LyXL5BvMXkfrCvb9HhvXQXKxLcKqydHMfjHCfu6Qcq0ES8nAW
; mTol1K1XH37t0rS20qaC70C+VbTKwDChlljcJOmnROFFJPVg2jHOBCfBzVQ8W6YgzY0sAMFtxz2shX
; h4BcEPuDr1y5ItMrP/zwg8zOQwqvVs8vGSE3O/HIfdF6pEPpzolc9eRsg3/C/vxs68k6Iexo7CUuD+
; s+RU28OgQk50RKBaFBeuXo0aMyRlNBc9hf2PUml5bKuJMYJ8pKQBBr6BQoqmE0jANcvJAuG0hzsZOR
; TAVpLt3Jx7XBOYsnhiQyvXoIDbZGkqtDqcb1NNW5yT/FTOQbETzOQFsXKIGiBv+EcYBLoaRzAuITPu
; HF6KYJ8l5REQ9wfwkdmEtk7dixQ24CJ9ZD7RYy3TJqMqKOSTvwgOjU1ADJsNRVQzpn6rhB691hriHd
; 5qRquMFRCRQ/xOP38BC05xHzI3QthAbx3s6dO2Udl6A5ii/sl4wkbamX0sbPTU+afGpzFg8F6RC/g3
; +iXjusDMaEUAZChvW+fq0ea0RfAM0pxKwYOd7PQnDQeaHKY1EvjB+oejKVAHoOkxIoDE3i84m11AEu
; OpAt1wOs6smqDu/3vfwSDyBiWTPcLqEd3yMjQjgTItcIVZ3gHKBkX+gowYLhHajJUs+msyeb1dN13U
; hzsW8HpcxDVMjvBiEea4K3wOUiaJWRq6WCk5LtfqHqyeQMvQbaQciHlSOwx3WoA1x0Jpsb7PVkBF6+
; awhCPICB4IGF+GxeU0bO+br/AflnOSZdOdCKAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R1
M73 Q0 S1
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.13.2 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling

G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line

G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.
M907 E430 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0

M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P5 R1
M73 Q4 S1
G1 E-.8 F2100
M73 P8 R1
M73 Q8 S1
G1 Z.4 F720
;AFTER_LAYER_CHANGE
;0.2
G1 X112.639 Y93.583 F10800
G1 Z.2 F720
M73 P9 R1
M73 Q9 S1
G1 E.8 F2100
M204 S800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X113.705 Y92.569 E.04613
G1 X115 Y92.246 E.04185
G1 X135 Y92.246 E.62709
G1 X136.417 Y92.639 E.04611
M73 P10 R1
M73 Q11 S1
G1 X137.431 Y93.705 E.04613
G1 X137.754 Y95 E.04185
M73 P11 R1
G1 X137.754 Y115 E.62709
G1 X137.361 Y116.417 E.04611
M73 P12 R1
M73 Q12 S1
G1 X136.295 Y117.431 E.04613
G1 X135 Y117.754 E.04185
M73 Q13 S1
G1 X115 Y117.754 E.62709
G1 X113.583 Y117.361 E.04611
M73 P14 R1
M73 Q14 S1
G1 X112.569 Y116.295 E.04613
G1 X112.246 Y115 E.04185
G1 X112.246 Y95 E.62709
G1 X112.623 Y93.64 E.04425
M204 S1000
M73 P15 R1
M73 Q16 S1
G1 X112.997 Y93.752 F10800
M204 S800
G1 F1200
G1 X113.015 Y93.693 E.00193
G1 X114.06 Y92.817 E.04275
G1 X115 Y92.623 E.03009
G1 X135 Y92.623 E.62709
G1 X136.307 Y93.015 E.04278
M73 P17 R1
M73 Q17 S1
G1 X137.183 Y94.06 E.04275
G1 X137.377 Y95 E.03009
G1 X137.377 Y115 E.62709
G1 X136.985 Y116.307 E.04278
M73 P18 R1
M73 Q19 S1
G1 X135.94 Y117.183 E.04275
G1 X135 Y117.377 E.03009
G1 X115 Y117.377 E.62709
M73 P19 R1
G1 X113.693 Y116.985 E.04278
M73 P20 R1
M73 Q20 S1
G1 X112.817 Y115.94 E.04275
G1 X112.623 Y115 E.03009
G1 X112.623 Y95 E.62709
G1 X112.979 Y93.81 E.03895
M204 S1000
; printing object one_layer_20x20.stl id:0 copy 0
;WIPE_START
M73 P21 R1
M73 Q22 S1
G1 F8640
M73 P21 R0
M73 Q22 S0
G1 X113.015 Y93.693 E-.02827
G1 X114.06 Y92.817 E-.31486
M73 P22 R0
G1 X115 Y92.623 E-.22162
G1 X116.019 Y92.623 E-.23525
;WIPE_END
G1 Z.6 F720
G1 X134.213 Y114.213 F10800
G1 Z.2 F720
M73 Q23 S0
G1 E.8 F2100
M204 S800
;TYPE:Perimeter
;WIDTH:0.419999
G1 F1200
G1 X115.787 Y114.213 E.57773
G1 X115.787 Y95.787 E.57773
M73 P24 R0
M73 Q24 S0
G1 X134.213 Y95.787 E.57773
M73 P25 R0
M73 Q25 S0
G1 X134.213 Y114.153 E.57585
M204 S1000
M73 P26 R0
M73 Q26 S0
G1 X134.59 Y114.59 F10800
M204 S800
;TYPE:External perimeter
M73 P27 R0
M73 Q28 S0
G1 F1200
G1 X115.41 Y114.59 E.60137
G1 X115.41 Y95.41 E.60137
M73 P29 R0
M73 Q29 S0
G1 X134.59 Y95.41 E.60137
M73 P30 R0
M73 Q30 S0
G1 X134.59 Y114.53 E.59949
M204 S1000
M73 P31 R0
M73 Q31 S0
G1 X134.204 Y114.486 F10800
;WIPE_START
M73 P32 R0
M73 Q33 S0
G1 F8640
G1 X131.125 Y114.541 E-.8
;WIPE_END
G1 Z.6 F720
G1 X134.043 Y96.731 F10800
M73 P33 R0
G1 Z.2 F720
G1 E.8 F2100
M204 S800
;TYPE:Solid infill
;WIDTH:0.425479
G1 F1200
G1 X133.439 Y96.126 E.02719
G1 X132.898 Y96.126 E.01721
G1 X133.874 Y97.102 E.04391
M73 Q34 S0
G1 X133.874 Y97.643 E.01721
G1 X132.357 Y96.126 E.06824
G1 X131.816 Y96.126 E.01721
G1 X133.874 Y98.184 E.09258
M73 P34 R0
G1 X133.874 Y98.725 E.01721
G1 X131.275 Y96.126 E.11692
G1 X130.734 Y96.126 E.01721
G1 X133.874 Y99.266 E.14126
G1 X133.874 Y99.807 E.01721
M73 Q35 S0
G1 X130.193 Y96.126 E.16559
G1 X129.652 Y96.126 E.01721
M73 P35 R0
G1 X133.874 Y100.348 E.18993
G1 X133.874 Y100.889 E.01721
M73 Q36 S0
G1 X129.111 Y96.126 E.21427
G1 X128.57 Y96.126 E.01721
M73 P36 R0
G1 X133.874 Y101.43 E.23861
G1 X133.874 Y101.971 E.01721
M73 Q37 S0
G1 X128.029 Y96.126 E.26294
G1 X127.488 Y96.126 E.01721
M73 P37 R0
G1 X133.874 Y102.512 E.28728
G1 X133.874 Y103.053 E.01721
M73 Q38 S0
G1 X126.947 Y96.126 E.31162
M73 P38 R0
G1 X126.406 Y96.126 E.01721
G1 X133.874 Y103.594 E.33596
M73 Q39 S0
G1 X133.874 Y104.135 E.01721
M73 P39 R0
G1 X125.865 Y96.126 E.36029
G1 X125.324 Y96.126 E.01721
M73 P40 R0
M73 Q40 S0
G1 X133.874 Y104.676 E.38463
G1 X133.874 Y105.217 E.01721
M73 P41 R0
M73 Q41 S0
G1 X124.783 Y96.126 E.40897
G1 X124.242 Y96.126 E.01721
M73 Q42 S0
G1 X133.874 Y105.758 E.43331
G1 X133.874 Y106.299 E.01721
M73 P42 R0
M73 Q43 S0
G1 X123.701 Y96.126 E.45764
G1 X123.16 Y96.126 E.01721
M73 P43 R0
M73 Q44 S0
G1 X133.874 Y106.84 E.48198
G1 X133.874 Y107.381 E.01721
M73 P44 R0
M73 Q45 S0
G1 X122.619 Y96.126 E.50632
G1 X122.078 Y96.126 E.01721
M73 P46 R0
M73 Q46 S0
G1 X133.874 Y107.922 E.53065
G1 X133.874 Y108.463 E.01721
M73 P47 R0
M73 Q47 S0
G1 X121.537 Y96.126 E.55499
G1 X120.996 Y96.126 E.01721
M73 P48 R0
M73 Q48 S0
G1 X133.874 Y109.004 E.57933
G1 X133.874 Y109.545 E.01721
M73 P49 R0
M73 Q49 S0
G1 X120.455 Y96.126 E.60367
G1 X119.914 Y96.126 E.01721
M73 P50 R0
M73 Q51 S0
G1 X133.874 Y110.086 E.628
G1 X133.874 Y110.627 E.01721
M73 P52 R0
M73 Q52 S0
G1 X119.373 Y96.126 E.65234
G1 X118.831 Y96.126 E.01724
M73 P53 R0
M73 Q53 S0
G1 X133.874 Y111.169 E.67672
G1 X133.874 Y111.71 E.01721
M73 P55 R0
M73 Q55 S0
G1 X118.29 Y96.126 E.70106
G1 X117.749 Y96.126 E.01721
M73 P56 R0
M73 Q56 S0
G1 X133.874 Y112.251 E.7254
G1 X133.874 Y112.792 E.01721
M73 P58 R0
M73 Q58 S0
G1 X117.208 Y96.126 E.74974
G1 X116.667 Y96.126 E.01721
M73 P59 R0
M73 Q59 S0
G1 X133.874 Y113.333 E.77407
M73 Q60 S0
G1 X133.873 Y113.874 E.01721
M73 P61 R0
M73 Q61 S0
G1 X116.126 Y96.127 E.79837
G1 X116.126 Y96.668 E.01721
M73 P63 R0
M73 Q63 S0
G1 X133.332 Y113.874 E.77403
G1 X132.791 Y113.874 E.01721
M73 P64 R0
M73 Q64 S0
G1 X116.126 Y97.209 E.74969
M73 Q65 S0
G1 X116.126 Y97.75 E.01721
M73 P66 R0
M73 Q66 S0
G1 X132.25 Y113.874 E.72535
G1 X131.709 Y113.874 E.01721
M73 P67 R0
M73 Q68 S0
G1 X116.126 Y98.291 E.70102
G1 X116.126 Y98.832 E.01721
M73 P69 R0
M73 Q69 S0
G1 X131.168 Y113.874 E.67668
G1 X130.627 Y113.874 E.01721
M73 P70 R0
M73 Q71 S0
G1 X116.126 Y99.373 E.65234
G1 X116.126 Y99.914 E.01721
M73 P72 R0
M73 Q72 S0
G1 X130.086 Y113.874 E.628
G1 X129.545 Y113.874 E.01721
M73 P73 R0
M73 Q73 S0
G1 X116.126 Y100.455 E.60367
G1 X116.126 Y100.996 E.01721
M73 P74 R0
M73 Q75 S0
G1 X129.004 Y113.874 E.57933
G1 X128.463 Y113.874 E.01721
M73 P76 R0
M73 Q76 S0
G1 X116.126 Y101.537 E.55499
G1 X116.126 Y102.078 E.01721
M73 P77 R0
M73 Q77 S0
G1 X127.922 Y113.874 E.53065
G1 X127.381 Y113.874 E.01721
M73 P78 R0
M73 Q78 S0
G1 X116.126 Y102.619 E.50632
G1 X116.126 Y103.16 E.01721
M73 P79 R0
M73 Q79 S0
G1 X126.84 Y113.874 E.48198
G1 X126.299 Y113.874 E.01721
M73 P80 R0
M73 Q80 S0
G1 X116.126 Y103.701 E.45764
G1 X116.126 Y104.242 E.01721
M73 P81 R0
M73 Q81 S0
G1 X125.758 Y113.874 E.43331
G1 X125.217 Y113.874 E.01721
M73 P82 R0
M73 Q82 S0
G1 X116.126 Y104.783 E.40897
G1 X116.126 Y105.324 E.01721
M73 P83 R0
M73 Q83 S0
G1 X124.676 Y113.874 E.38463
G1 X124.135 Y113.874 E.01721
M73 P84 R0
M73 Q84 S0
G1 X116.126 Y105.865 E.36029
G1 X116.126 Y106.406 E.01721
M73 P85 R0
M73 Q85 S0
G1 X123.594 Y113.874 E.33596
G1 X123.053 Y113.874 E.01721
G1 X116.126 Y106.947 E.31162
M73 Q86 S0
G1 X116.126 Y107.488 E.01721
M73 P86 R0
G1 X122.512 Y113.874 E.28728
G1 X121.971 Y113.874 E.01721
M73 P87 R0
M73 Q87 S0
G1 X116.126 Y108.029 E.26294
G1 X116.126 Y108.57 E.01721
G1 X121.43 Y113.874 E.23861
G1 X120.889 Y113.874 E.01721
M73 P88 R0
M73 Q88 S0
G1 X116.126 Y109.111 E.21427
G1 X116.126 Y109.652 E.01721
G1 X120.348 Y113.874 E.18993
G1 X119.807 Y113.874 E.01721
M73 P89 R0
M73 Q89 S0
G1 X116.126 Y110.193 E.16559
G1 X116.126 Y110.734 E.01721
G1 X119.266 Y113.874 E.14126
G1 X118.725 Y113.874 E.01721
M73 P90 R0
M73 Q90 S0
G1 X116.126 Y111.275 E.11692
G1 X116.126 Y111.816 E.01721
G1 X118.184 Y113.874 E.09258
G1 X117.643 Y113.874 E.01721
G1 X116.126 Y112.357 E.06824
G1 X116.126 Y112.898 E.01721
G1 X117.102 Y113.874 E.04391
G1 X116.561 Y113.874 E.01721
G1 X115.957 Y113.269 E.02719
M204 S1000
; stop printing object one_layer_20x20.stl id:0 copy 0
;WIPE_START
M73 Q91 S0
G1 F8640;_WIPE
M73 P91 R0
G1 X116.561 Y113.874 E-.1974
G1 F8640;_WIPE
G1 X117.102 Y113.874 E-.12492
G1 F8640;_WIPE
G1 X116.126 Y112.898 E-.31871
G1 F8640;_WIPE
G1 X116.126 Y112.357 E-.12492
G1 F8640;_WIPE
G1 X116.23 Y112.461 E-.03405
;WIPE_END
G1 Z.6 F720
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z1.2 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
G1 Z49.2 F720 ; Move print head further up
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA
M907 E538 ; reset extruder motor current
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M84 ; disable motors
; max_layer_z = 0.2
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 59.53
; filament used [cm3] = 0.14
; filament used [g] = 0.18
; filament cost = 0.01
; total filament used [g] = 0.18
; total filament cost = 0.01
; estimated printing time (normal mode) = 1m 16s
; estimated printing time (silent mode) = 1m 16s
; estimated first layer printing time (normal mode) = 1m 16s
; estimated first layer printing time (silent mode) = 1m 16s

; prusaslicer_config = begin
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and printer_notes!~/.*PG.*/  and printer_notes!~/.*MINIIS.*/ and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 36.29
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusament PLA"
; filament_soluble = 0
; filament_spool_weight = 193
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 10%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 10
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0\n\n{if printer_notes=~/.*PRINTER_MODEL_MINIIS.*/}\nM572 S{if nozzle_diameter[0]==0.6}0.17{elsif nozzle_diameter[0]==0.8}0.12{elsif nozzle_diameter[0]==0.4}0.3{elsif nozzle_diameter[0]==0.25}0.85{else}0{endif}\n{endif}"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.13.2 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 30
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 3
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.6
; support_tree_top_rate = 30%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 8
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
